# Site settings
title: "glastonauts.live"
description: Community lockdown radio


# Files
baseurl:
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png
# discus_shortname: MADness
email: uncoolbob@gmail.com
#
# can change this to http://glastonauts.live when we deploy it
url: https://glastonauts.live
#url: "http://127.0.0.1:4000"
#url: http://185.225.210.89
#protocol: http
protocol: https
#

search: true
share: true
comments: true

gallery_folder_name: gallery


icecast: "https://glastonauts.live/stream"

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name:   glastonauts
  avatar: avatar.jpg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    glastonauts

# Social networking links used in footer. Update and remove as you like.
#twitter_username: MAD4Jekyll
#facebook_username: MAD4Jekyll
#github_username: MAD4Jekyll
#deviantart_username: MAD4Jekyll
#500px_username: MAD4Jekyll
#flickr_username: MAD4Jekyll
#instagram_username: MAD4Jekyll

 
# Internal nav
nav:
 writing: "root_url/writing/"
 gallery: "root_url/gallery/"
 about: "root_url/about/"
 title: "lakis"


# Server
destination:      	 ./_site
port:             	 4000


#dependencies
# Gems
#gems:
#  - jekyll-paginate


# Build settings
highlighter:         rouge
markdown:           kramdown
kramdown:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
#paginate: 5
#paginate_path: "/writing/page:num/"
#permalink: "/writing/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-162091652-1
# google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         
